[tools]
pnpm = "11"
python = "3.12"
ruff = "0.14"
ty = "0.0"
uv = "0.9"
node = "24"

[settings]
python.uv_venv_auto = true
experimental = true

[hooks]
postinstall = "mise run activate"

[tasks.activate]
description = "activates the config"
alias = "a"
run = "corepack enable"
