FROM debian:13-slim

RUN apt-get update \
    && apt-get -y --no-install-recommends install \
        sudo curl git ca-certificates build-essential \
    && rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
ENV MISE_DATA_DIR="/mise"
ENV MISE_CONFIG_DIR="/mise"
ENV MISE_CACHE_DIR="/mise/cache"
ENV MISE_INSTALL_PATH="/usr/local/bin/mise"
ENV PATH="/mise/shims:$PATH"

RUN curl https://mise.run | sh

WORKDIR /workspace

COPY mise.toml mise.lock ./
RUN mise trust && mise install

COPY pyproject.toml uv.lock ./
RUN mise exec -- uv sync

COPY .buildkite/scripts/test.sh eslint.config.mjs package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN mise exec -- corepack enable && \
    mise exec -- pnpm install --frozen-lockfile

COPY index.js ./index.js
COPY tests ./tests
